apiVersion: v1
kind: Pod

metadata:
  name: ubuntu-sleeper-pod
  labels:
    app: ubuntu-sleeper
spec:
  containers:
  - name: ubuntu-sleeper-container
    image: ubuntu
    # command is the ENTRYPOINT and args is the CMD of the docker arguments:
    command: ["sleep"]
    args: ["10"]